services:
  - type: web
    name: skillcohort-api
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://skillcohort.vercel.app
      - key: COOKIE_DOMAIN
        value: skillcohort.vercel.app
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
